### ISSUE TITLE
add .editorconfig to this repo

### ISSUE THREAD

**Issue by makotot** [symdiff/grunt-symdiff#3]
This is a proposal.
I think [editorconfig](http://editorconfig.org/) would be useful in [this situation](https://github.com/symdiff/grunt-symdiff/pull/1#discussion_r30274585).

**Comment by prayerslayer** [comment]
Ah sorry, I mixed up the PR and the issue. So to have it here again: I agree we should not be arguing about indentation, but I’d prefer a `.jscsrc` file with an appropriate Grunt task as a solution.

**Comment by makotot** [comment]
@prayerslayer I agree with your idea.

**Comment by prayerslayer** [comment]
Fixed with #5
